version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    volumes:
      - ./server:/app
    working_dir: /app
    command: node index.js
    ports:
      - "4000:4000"
    depends_on:
      - mongo

volumes:
  mongo_data:
